name: 'Build the IG'

on:
  workflow_dispatch: # On manual trigger
  push:
    branches: [ master, validation ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: 'Run the validator on resource samples'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@v3

      - name: 'Build the IG'
        uses: qligier/fhir-ig-action@3afbc80016c385580e0d7f6265684a0e59eff5c3
